feat: Database-setup
BuildForSDG/mentel pull request #18
Opened 2020-05-08 10:14 UTC by AbonyiXavier

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-08 10:27 UTC, neymarjimoh requested changes
use double quotes

2020-05-10 11:56 UTC, Kibetchirchir requested changes

2020-05-10 11:56 UTC, Kibetchirchir commented on server/app.js
> +const PORT = process.env.PORT || 500;
Use 5000 instead. Since 500 is already set and not available

2020-05-10 11:56 UTC, Kibetchirchir commented on server/app.js
> +});
use a different file to setup the DB and connection

2020-05-10 11:56 UTC, Kibetchirchir commented on server/config/config.json
> +    "operatorsAliases": false
Use `dotenv` to store sensitive data that can be used to exploit your app
check `dotenv` np package

2020-05-10 12:08 UTC, sadiqasg submitted a review, later dismissed
This looks good @AbonyiXavier ,
Good call with adding babel

2020-05-10 13:13 UTC, neymarjimoh submitted a review, later dismissed
Nice idea adding Babel.

2020-05-11 13:13 UTC, sadiqasg approved these changes
Looking good

2020-05-11 14:43 UTC, merged