I created a new branch and worked directly on the files from the repo…
BuildForSDG/mentel pull request #19
Opened 2020-05-10 15:17 UTC by silvertechhub

…, and I also reviewed the error from the previous commit. also check out the login and signup pages

#
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-10 19:31 UTC, neymarjimoh submitted a review, later dismissed

2020-05-11 14:32 UTC, neymarjimoh submitted a review, later dismissed

2020-05-11 14:51 UTC, sadiqasg requested changes
Nice Job.
But your lottie animated image is not rendering.
Add this `  <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>` to the end of your /public/index.html file. And we are good to go!

2020-05-11 15:02 UTC, sadiqasg approved these changes

2020-05-11 15:04 UTC, merged