adding landing page files
BuildForSDG/mentel pull request #6
Opened 2020-05-06 09:14 UTC by silvertechhub

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-08 10:15 UTC, sadiqasg requested changes
Your strings should use double quotes.
End your blocks of code with a semi-colon;
Use strong equality sign "!=="

2020-05-10 12:42 UTC, sadiqasg requested changes
Dont name your folder with spaces inbetween.
Also, your ladning page should be your inital page. (i.e it should take the place of /src/App.js or be returned in it

2020-05-10 13:20 UTC, neymarjimoh requested changes
Follow the codacy rules for use of double quotes instead of single quote.and semi-colons where necessary. In all, it's ok but static for now

2020-05-10 13:20 UTC, neymarjimoh commented on client/src/landing page/App.css
> +  }
Delete any pre-bulit css styles that is not needed

2020-05-11 13:03 UTC, closed without merging